public class wrapperClassOfHubspotAss 
{
    public cls_results[] results;
    public class cls_results 
    {
        public String id;	//1
        public cls_properties properties;
        public String createdAt;	//2022-06-10T05:42:40.093Z
        public String updatedAt;	//2022-06-10T05:42:46.756Z
        public boolean archived;
    }
    public class cls_properties 
    {
        public String createdate;	//2022-06-10T05:42:40.093Z
        public String email;	//emailmaria@hubspot.com
        public String firstname;	//Maria
        public String hs_object_id;	//1
        public String lastmodifieddate;	//2022-06-10T05:42:46.756Z
        public String lastname;	//Johnson (Sample Contact)
    }
}